### ISSUE TITLE
Source lua files in plugin/ folders instead of or beside lua/plugin/

### ISSUE THREAD

**Issue by kutsan** [tjdevries/astronauta.nvim#2]
It would also good to have first-class support for lua files in standard plugin folders. Although, I guess it can't be achieved with current limitations.

**Comment by clason** [comment]
That is being implemented upstream already: https://github.com/neovim/neovim/pull/14686

**Comment by Corey-Keller** [comment]
> That is being implemented upstream already: [neovim/neovim#14686](https://github.com/neovim/neovim/pull/14686)

@clason @tjdevries 
Does that PR (that I assume is in 0.5 stable?) make the that part of this plugin irrelevant? Or does it still provide more than 0.5 stable does in regards to where *.lua is sourced?

And, if my above assumption is correct, does that mean that this plugin is only needed if being used for the actual mapping functionality? I ask because I'm currently using [which-key.nvim](https://github.com/folke/which-key.nvim) for my mapping.

**Comment by gegoune** [comment]
Also I have found lua sourcing part of that plugin to weight heavily on my startup time so I had it disabled for quite a while.

```lua
vim.g.astronauta_load_plugins = false
```

Perhaps it could be removed from that plugin, or change the default of above to false? I will be using astronauta until lua callbacks in mappings are implemented in core.

Thanks for that @tjdevries !

**Comment by tjdevries** [comment]
I've removed loading plugins and ftplugins from this repo. It is in nvim core, so no need to do it a different way.

Thanks :)
